FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY vite.config.ts ./
COPY tsconfig.json ./
COPY index.html ./

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
